apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: documind-ingress
  namespace: documind
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "60m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
spec:
  ingressClassName: nginx
  rules:
    - host: documind.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: documind-api
                port:
                  number: 80
