apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "documind.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "documind.labels" . | nindent 4 }}
    app: documind-api
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "documind.selectorLabels" . | nindent 6 }}
      app: documind-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        {{- include "documind.selectorLabels" . | nindent 8 }}
        app: documind-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ include "documind.fullname" . }}-config
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8000
            initialDelaySeconds: 45
            periodSeconds: 10
            failureThreshold: 5
      terminationGracePeriodSeconds: 30
