{{- if .Values.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "documind.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "documind.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.api.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.api.ingress.className }}
  rules:
    - host: {{ .Values.api.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "documind.fullname" . }}-api
                port:
                  number: {{ .Values.api.service.port }}
{{- end }}
